#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header$

PIDFILE=/var/run/kamailio.pid

depend() {
	need net
}

start() {
	ebegin "Starting Kamailio"
	start-stop-daemon --start --quiet --pidfile "${PIDFILE}" \
		--exec /usr/sbin/kamailio -- -P "${PIDFILE}" ${KAMAILIO_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping Kamailio"
	start-stop-daemon --stop --quiet --pidfile "${PIDFILE}"
	eend $?
}

